import http from '@/http';
import { Product } from '@/model';
import { Typography, Button, ListItem, ListItemAvatar, Avatar, ListItemText, TextField, Grid, Box } from '@material-ui/core';
import { GetServerSideProps, NextPage } from 'next';
import Head from 'next/head';
import React from 'react';
import axios from 'axios';

interface OrderPageProps {
    product: Product
}

const OrderPage: NextPage<OrderPageProps> = ({ product }) => {



    return (
        <div>
            <Head>
                <title>Pagamento</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
            <Typography
                component="h1"
                variant="h3"
                color="textPrimary"
                gutterBottom
            >
                Checkout
            </Typography>

            <ListItem>
                <ListItemAvatar>
                    <Avatar src={product.image_url} />
                </ListItemAvatar>
                <ListItemText primary={product.name} secondary={`R$ ${product.price}`} primaryTypographyProps={{ color: "textPrimary" }} />
            </ListItem>

            <Typography
                component="h2"
                variant="h5"
                color="textPrimary"
                gutterBottom
            >
                Pague com cartão de crédito
            </Typography>

            <form>
                <Grid container spacing={3}>
                    <Grid item xs={12} md={6}>
                        <TextField required label="Nome" fullWidth />
                    </Grid>
                    <Grid item xs={12} md={6}>
                        <TextField required label="Numero do cartão" fullWidth inputProps={{
                            maxLength: 16
                        }} />
                    </Grid>
                    <Grid item xs={12} md={6}>
                        <TextField required type="number" label="CVV" fullWidth />
                    </Grid>
                    <Grid item xs={12} md={6}>
                        <Grid container spacing={3}>
                            <Grid item xs={6}>
                                <TextField required type="number" label="Expiração mês" fullWidth />
                            </Grid>
                            <Grid item xs={6}>
                                <TextField required type="number" label="Expiração ano" fullWidth />
                            </Grid>
                        </Grid>
                    </Grid>
                    <Button style={{
                        marginTop: 20
                    }} type="submit" variant="contained" color="primary" fullWidth>Pagar</Button>
                </Grid>
            </form>

        </div>
    );
}


export default OrderPage;

export const getServerSideProps: GetServerSideProps<OrderPageProps> = async (context) => {
    const { slug } = context.params!

    try {
        const { data: product } = await http.get(`products/${slug}`)
        return {
            props: {
                product
            },
        }
    } catch (e) {
        if (axios.isAxiosError(e) && e.response?.status === 404) {
            return {
                notFound: true
            }
        }
        throw e;
    }

}
